version: "3"
services:

  nginx:
    container_name: nginx
    image: nginx:1.17-alpine
    restart: always
    ports:
      - 80:80
      # - 443:443
      - 9999:9999
      - 19999:19999
      - 19998:19998
      # - 3001:3001
      # - 3003:3003
      # - 3004:3004
      # - 3007:3007
      # - 3020:3020
      # - 3021:3021
      # - 3023:3023
    networks:
      - nginx-network
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/conf.d:/etc/nginx/conf.d
      # 日志文件
      - ../docker_data/nginx/log:/var/log/nginx/
      # web部署
      - /Users/suwei/WorkSpace/Personal/net-pay/web/dist:/app/net-pay/web/
      - /Users/suwei/WorkSpace/Personal/vk-food/web/dist:/app/net-pay/web/vkfood/

networks:
  nginx-network:
    driver: bridge