version: "3"
services:

  mongo:
      container_name: mongo
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ../docker_data/mongo/data:/data
      networks:
        - mongo-network
      environment: #environment 和 Dockerfile 中的 ENV 指令一样会把变量一直保存在镜像、容器中，类似 docker run -e 的效果。设置容器的环境变量
        - TZ=Asia/Shanghai
      restart: always

networks:
  mongo-network:
    driver: bridge